---
- name: Create selenoid workdir
  file:
    path: /root/selenoid_pro
    state: directory
    mode: '0666'

- name: Running selenoid
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /root/selenoid_otus
