---
- name: Create selenoid_otus directory
  file:
    path: /root/selenoid_otus
    state: directory
    mode: '0755'

- name: Create browser.json
  template:
    src: ../../templates/browsers.json.j2
    dest: /root/selenoid_otus/browsers.json
  vars:
    default_chrome_version: "128.0"
    default_firefox_version: "121.0"
    chrome_browsers:
      "128.0":
        image: "selenoid/vnc:chrome_128.0"
        port: "4444"
        path: "/"
      "127.0":
        image: "selenoid/vnc:chrome_127.0"
        port: "4444"
        path: "/"
    firefox_browsers: {}

- name: Create docker compose.yaml
  template:
    src: ../../templates/docker-compose.yaml.j2
    dest: /root/selenoid_otus/docker-compose.yaml

- name: Create ggr/grid-router folder
  file:
    path: /root/selenoid_otus/ggr/grid-router
    state: directory
    mode: '0755'

- name: Create users.httpasswd
  template:
    src: ../../templates/users.httpasswd.j2
    dest: /root/selenoid_otus/ggr/grid-router/users.httpasswd
  vars:
    user: root

- name: Create quota dir for ggr
  file:
    path: /root/selenoid_otus/ggr/grid-router/quota
    state: directory
    mode: '0666'

- name: Create ggr balancer rules
  template:
    src: ../../templates/test.xml.j2
    dest: /root/selenoid_otus/ggr/grid-router/quota/artemn.xml
  vars:
    chrome_versions:
      - "128.0"
      - "127.0"
    selenoid_hosts:
      - selenoid1
      - selenoid2

- name: Create nginx folder
  file:
    path: /root/selenoid_otus/nginx
    state: directory
    mode: '0666'

- name: Create nginx selenoid.conf
  template:
    src: ../../templates/selenoid.conf.j2
    dest: /root/selenoid_otus/nginx/selenoid.conf
  vars:
    nginx_port: 80
    selenoid_ui: 8080
    ggr_port: 4444
